version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: cd frontend && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "frontend/package-lock.json" }}
          paths:
            - ./frontend/node_modules
      - run: cd frontend && npm run build
  deploy:
    docker:
      - image: circleci/node:8
    environment:
      - NODE_ENV: prod
    steps:
      - checkout
      - run: cd frontend && npm install
      - run: cd backend && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "frontend/package-lock.json" }}
          paths:
            - ./frontend/node_modules
      - run: cd frontend && npm run build
      - run: scripts/deploy.sh
    branches:
      only:
        - develop
        - master