version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
            keys:
              - dependency-cache-{{ checksum "frontend/yarn.lock" }}
      - run: cd frontend && yarn
      - save_cache:
          key: dependency-cache-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ./frontend/node_modules
      - run: cd frontend && yarn build
  deploy:
    docker:
      - image: circleci/node:8
    environment:
      - NODE_ENV: prod
    steps:
      - checkout
      - run: cd frontend && yarn
      - run: cd backend && npm install --production
      - run: cd frontend && yarn build
      - add_ssh_keys:
          fingerprints:
            - "10:0d:a6:f2:e7:1b:65:be:f6:e2:31:95:ce:0c:99:97"
      - run: scripts/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /frontend\/*/
                - develop
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop